version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  buildlinux:
    working_directory: ~/telescope
    docker:
      - image: circleci/node:lts
      - image: circleci/redis:latest 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Execute tests
          command: npm test
  buildwindows:
    executor:
      name: win/vs2019
      shell: bash.exe
    working_directory: ~/telescope
    steps: 
      - checkout
      - run:
          command: |
            cd ../
            mv $CIRCLE_WORKING_DIRECTORY _old
            git config --global core.autocrlf false
            git clone --depth=50 _old $CIRCLE_WORKING_DIRECTORY
            cd $CIRCLE_WORKING_DIRECTORY
            npm ci
            npm test
         
         
workflows:
  myworkflows:
    jobs:
      - buildlinux
      - buildwindows
